SHOW DATABASES;
CREATE DATABASE MYDATABASE;
USE MYDATABASE;      -- (FOR JDBC)
SHOW TABLES;

-- WORK ON EMPLOYEES TABLE
CREATE TABLE EMPLOYEES(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
JOB_TITLE VARCHAR(255),
SALARY DOUBLE
);
DESC EMPLOYEES;
INSERT INTO EMPLOYEES (ID,NAME,JOB_TITLE,SALARY) VALUES
(0,"KUNAL","SOFTWARE DEVELOPER",75000.0),
(2,"HEMANT","DEVOPS ENGINEER",65000.0);
SELECT * FROM EMPLOYEES;

-- WORK ON IMAGE TABLE
CREATE TABLE IMAGES(
IMAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
IMAGE_DATA LONGBLOB NOT NULL,
UPLOAD_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DESC IMAGES;
SELECT * FROM IMAGES;

-- WORK ON ACCOUNTS TABLE
CREATE TABLE ACCOUNTS(
ACCOUNT_NUMBER VARCHAR(20) PRIMARY KEY,
BALANCE DECIMAL(10,2) NOT NULL
);
DESC ACCOUNTS;
INSERT INTO ACCOUNTS (ACCOUNT_NUMBER,BALANCE) VALUES
("account123",1000.00),
("account456",500.00),
("account789",750.50);
SELECT * FROM ACCOUNTS;



-- PROJECT HOTEL_RESERVATION_SYSTEM
SHOW DATABASES;
CREATE DATABASE HOTEL_DB;
USE HOTEL_DB;      
SHOW TABLES;
-- WORK ON RESERVATIONS TABLE
CREATE TABLE RESERVATIONS(
RESERVATION_ID INT AUTO_INCREMENT PRIMARY KEY,
GUEST_NAME VARCHAR(255) NOT NULL,
ROOM_NUMBER INT NOT NULL,
CONTACT_NUMBER VARCHAR(10) NOT NULL,
RESERVATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DESC RESERVATIONS;
SELECT * FROM RESERVATIONS;


-- PROJECT BANKING_SYSTEM
SHOW DATABASES;
    CREATE DATABASE BANKING_SYSTEM;
USE BANKING_SYSTEM;      
SHOW TABLES;
-- WORK ON ACCOUNTS TABLE
CREATE TABLE ACCOUNTS(
ACCOUNT_NUMBER BIGINT PRIMARY KEY,
FULL_NAME VARCHAR(255) NOT NULL ,
EMAIL VARCHAR(255) UNIQUE NOT NULL,
BALANCE DECIMAL(10,2) NOT NULL,
SECURITY_PIN CHAR(4) NOT NULL 
);
INSERT INTO ACCOUNTS (ACCOUNT_NUMBER,FULL_NAME,EMAIL,BALANCE,SECURITY_PIN) VALUES
(1000230,"DIYA","23@",2345,1234),
(1000330,"CHARU","76@",6789,5678);
SELECT ACCOUNT_NUMBER FROM ACCOUNTS order by ACCOUNT_NUMBER DESC LIMIT 1;
DESC ACCOUNTS;
SELECT * FROM ACCOUNTS;
DROP TABLE ACCOUNTS;
-- WORK ON USER TABLE
CREATE TABLE USER(
FULL_NAME VARCHAR(255)  NOT NULL,
EMAIL VARCHAR(255) PRIMARY KEY NOT NULL,
PASSWORD VARCHAR(255)  NOT NULL
);
DESC USER;
SELECT * FROM USER;


-- PROJECT HOSPITAL_MANAGEMENT_SYSTEM
SHOW DATABASES;
CREATE DATABASE HOSPITAL;
USE HOSPITAL;      
SHOW TABLES;
-- WORK ON PATIENTS TABLE
CREATE TABLE PATIENTS(
PAT_ID INT PRIMARY KEY AUTO_INCREMENT,
FULL_NAME VARCHAR(255) NOT NULL ,
AGE INT NOT NULL,
GENDER VARCHAR(10) NOT NULL
);
DESC PATIENTS;
SELECT * FROM PATIENTS;

-- WORK ON DOCTORS TABLE
CREATE TABLE DOCTORS(
DOC_ID INT PRIMARY KEY AUTO_INCREMENT,
FULL_NAME VARCHAR(255) NOT NULL ,
SPECILIZATION VARCHAR(255) NOT NULL
);
DESC DOCTORS;
insert into doctors(full_name,specilization) values("Pankaj jain","Physician"),("Harshit amod","NeuroSurgeon");
SELECT * FROM DOCTORS;


-- WORK ON APPOINTMENTS TABLE
CREATE TABLE APPOINTMENTS(
ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENT_ID INT NOT NULL,
DOCTOR_ID INT NOT NULL,
APPOINTMENT_DATE DATE NOT NULL,
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PAT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOC_ID)
);
DESC APPOINTMENTS;
SELECT * FROM APPOINTMENTS;



drop table doctors;
drop table patients;
drop table appointments;

